site_name: Snom io Knowledge base
#theme: readthedocs
theme_dir: 'mkdocs-bootstrap-snom'
#theme_dir: 'bootswatch-yeti-snom'
copyright: 'Copyright © 2016 Snom Technology AG. All rights reserved.'
pages:
    - Home: index.md
    - XML Minibrowser:
        - 'Introduction': xml_minibrowser/index.md
        - 'Main tags': 
            - 'SnomIPPhoneMenu': xml_minibrowser/main_tags/SnomIPPhoneMenu.md
            - 'SnomIPPhoneDirectory': xml_minibrowser/main_tags/SnomIPPhoneDirectory.md
            - 'SnomIPPhoneText': xml_minibrowser/main_tags/SnomIPPhoneText.md 
            - 'SnomIPPhoneImage': xml_minibrowser/main_tags/SnomIPPhoneImage.md
            - 'SnomIPPhoneImageFile': xml_minibrowser/main_tags/SnomIPPhoneImageFile.md
            - 'SnomIPPhoneInput': xml_minibrowser/main_tags/SnomIPPhoneInput.md
            - 'SnomIPPhoneBatch': xml_minibrowser/main_tags/SnomIPPhoneBatch.md
            - 'Main Sub Tags': xml_minibrowser/main_tags/main_sub_tags.md
            - 'Main Attributes': xml_minibrowser/main_tags/MainAttributes.md
        - 'Callbacks':
            - 'Introduction': xml_minibrowser/callbacks/index.md
            - 'hiddenpages': 
                - 'arch_series': xml_minibrowser/examples/cb_arch_series.md
                - 'bool_eval': xml_minibrowser/examples/cb_bool_eval.md
                - 'checkbox_property': xml_minibrowser/examples/cb_checkbox_property.md
                - 'condition': xml_minibrowser/examples/cb_condition.md
                - 'create_url': xml_minibrowser/examples/cb_create_url.md
                - 'current_input': xml_minibrowser/examples/cb_current_input.md
                - 'current_line': xml_minibrowser/examples/cb_current_line.md
                - 'date': xml_minibrowser/examples/cb_date.md
                - 'time': xml_minibrowser/examples/cb_time.md
                - 'display_type': xml_minibrowser/examples/cb_display_type.md
                - 'edit_mode': xml_minibrowser/examples/cb_edit_mode.md
                - 'empty': xml_minibrowser/examples/cb_empty.md
                - 'enum': xml_minibrowser/examples/cb_enum.md
                - 'fragment': xml_minibrowser/examples/cb_fragment.md
                - 'lang': xml_minibrowser/examples/cb_lang.md 
                - 'lastsel': xml_minibrowser/examples/cb_lastsel.md 
                - 'lines': xml_minibrowser/examples/cb_lines.md 
                - 'list_size': xml_minibrowser/examples/cb_list_size.md
                - 'math_eval': xml_minibrowser/examples/cb_math_eval.md 
                - 'max_registrations': xml_minibrowser/examples/cb_max_registrations.md
                - 'max_pkeys': xml_minibrowser/examples/cb_max_pkeys.md
                - 'mod_ifc': xml_minibrowser/examples/cb_mod_ifc.md
                - 'module_id_of_current_line': xml_minibrowser/examples/cb_module_id_of_current_line.md
                - 'on_off': xml_minibrowser/examples/cb_on_off.md
                - 'phone_state': xml_minibrowser/examples/cb_phone_state.md
                - 'remove_cmd': xml_minibrowser/examples/cb_remove_cmd.md
                - 'set': xml_minibrowser/examples/cb_set.md
                - 'setcache': xml_minibrowser/examples/cb_setcache.md
                - 'cb_show_feature': xml_minibrowser/examples/cb_show_feature.md
                - 'status_message': xml_minibrowser/examples/cb_status_message.md
                - 'urlencode': xml_minibrowser/examples/cb_urlencode.md
                - 'user_displayname': xml_minibrowser/examples/cb_user_displayname.md
                - 'var': xml_minibrowser/examples/cb_var.md
                - 'cb_var_ifc': xml_minibrowser/examples/cb_var_ifc.md
                - 'cb_wifiscan': xml_minibrowser/examples/cb_wifiscan.md
                - 'cb_wlang': xml_minibrowser/examples/cb_wlang.md
                - 'x_o': xml_minibrowser/examples/cb_x_o.md
                - 'yes_no': xml_minibrowser/examples/cb_yes_no.md
                - 'boolean callbacks': xml_minibrowser/examples/cb_boolean_callbacks.md
        - 'Fragments':
            - 'Introduction': xml_minibrowser/fragments/index.md
            - 'hiddenpages':
                - 'setcache': xml_minibrowser/examples/fr_setcache.md
                - 'clearcache': xml_minibrowser/examples/fr_clearcache.md
                - 'clearvar': xml_minibrowser/examples/fr_clearvar.md
                - 'menu': xml_minibrowser/examples/fr_menu.md
                - 'fr_next_edit_mode': xml_minibrowser/examples/fr_next_edit_mode.md
                - 'sel': xml_minibrowser/examples/fr_sel.md
                - 'fr_reloadset': xml_minibrowser/examples/fr_reloadset.md
                - 'set': xml_minibrowser/examples/fr_set.md
                - 'sub': xml_minibrowser/examples/fr_sub.md
                - 'toggleset': xml_minibrowser/examples/fr_toggleset.md
                - 'var': xml_minibrowser/examples/fr_var.md
                - 'action_ifc': xml_minibrowser/examples/fr_action_ifc.md
                - 'applyline': xml_minibrowser/examples/fr_applyline.md
                - 'key': xml_minibrowser/examples/fr_key.md
                - 'numberdial': xml_minibrowser/examples/fr_numberdial.md
                - 'reboot': xml_minibrowser/examples/fr_reboot.md
                - 'reregister': xml_minibrowser/examples/fr_reregister.md
                - 'unregister': xml_minibrowser/examples/fr_unregister.md
                - 'var_ifc': xml_minibrowser/examples/fr_var_ifc.md
                - 'mjpg': xml_minibrowser/examples/fr_mjpg.md
        - 'Builtin Templates': xml_minibrowser/templates.md
        - 'Examples':
            - 'Introduction': xml_minibrowser/examples/index.md
            - 'SnomIPPhoneText': xml_minibrowser/examples/SnomIPPhoneText.md
            - 'SnomIPPhoneMenu': xml_minibrowser/examples/SnomIPPhoneMenu.md
            - 'InputField': xml_minibrowser/examples/InputField.md
            - 'SnomIPPhoneDirectory': xml_minibrowser/examples/SnomIPPhoneDirectory.md
            - 'SnomIPPhoneInput': xml_minibrowser/examples/SnomIPPhoneInput.md
            - 'SnomIPPhoneImage': xml_minibrowser/examples/SnomIPPhoneImage.md
            - 'SnomIPPhoneImageFile': xml_minibrowser/examples/SnomIPPhoneImageFile.md
            - 'SnomIPPhoneBatch': xml_minibrowser/examples/SnomIPPhoneBatch.md
            - 'Main sub elements': xml_minibrowser/examples/main_subelements.md
            - 'Main elements attributes': xml_minibrowser/examples/main_elements_attributes.md

extra_css: [extra.css]
markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - markdown_include.include
  - toc:
      permalink: " #"
      separator: "_"
